select nvl( sum(IMPORTE) , 0)  from SD_INGRESOS  where ID_CAJA = 9 and ESTADO != 'ANULADO'
                             AND FECHA BETWEEN TO_DATE('01-03-2025', 'DD-MM-YYYY')
        AND TO_DATE('01-08-2025', 'DD-MM-YYYY');


select nvl( sum(IMPORTE) , 0 )  from SD_TRANSFERENCIAS where ID_CAJA_DESTINO = 9 and ESTADO != 'ANULADO'
                                  AND FECHA BETWEEN TO_DATE('01-03-2025', 'DD-MM-YYYY')
        AND TO_DATE('01-08-2025', 'DD-MM-YYYY');

select nvl(sum(IMPORTE_PRESTAMO) , 0) from SD_PRESTAMOS_POR_SOCIOS where ESTADO != 'ANULADO' and FECHA BETWEEN TO_DATE('01-03-2025', 'DD-MM-YYYY')
    AND TO_DATE('01-08-2025', 'DD-MM-YYYY');

select nvl( sum(IMPORTE) ,0) as importe , nvl (sum(IMPORTE_MORA) ,0) as moras , nvl(sum(TOTAL_CONDONACION),0) from SD_PAGO_DE_PRESTAMOS where ID_CAJA = 9 and ESTADO != 'ANULADO' and FECHA  BETWEEN TO_DATE('01-03-2025', 'DD-MM-YYYY')
    AND TO_DATE('01-08-2025', 'DD-MM-YYYY');
select IMPORTE_MORA , IMPORTE , TOTAL_CONDONACION from SD_PAGO_DE_PRESTAMOS where ID_CAJA = 9 and ESTADO != 'ANULADO' and FECHA  BETWEEN TO_DATE('01-03-2025', 'DD-MM-YYYY')
    AND TO_DATE('01-08-2025', 'DD-MM-YYYY');
select sum from SD_PAGO_DE_PRESTAMOS where ID_CAJA = 9 and ESTADO != 'ANULADO' and FECHA  BETWEEN TO_DATE('01-03-2025', 'DD-MM-YYYY')
    AND TO_DATE('01-08-2025', 'DD-MM-YYYY') and ID_PRESTAMO = 105;

select * from SD_PRESTAMOS_POR_SOCIOS  where ID_PRESTAMO = 105;

select INGRESO - EGRESO from SD_KARDEX_EFECTIVO where ID_CAJA = 9;
select * from SD_KARDEX_EFECTIVO where ID_CAJA = 9;

select sum(INGRESO - EGRESO) from SD_KARDEX_EFECTIVO where ID_CAJA = 9
select sum(EGRESO)
from SD_KARDEX_EFECTIVO
where ID_CAJA = 9
  and EGRESO > 0 and OPERACION = 'PRESTAMOS';

select sum(INGRESO)
from SD_KARDEX_EFECTIVO
where ID_CAJA = 9 and OPERACION = 'PAGO PRESTAMO';

select OPERACION , count(1) from SD_KARDEX_EFECTIVO where ID_CAJA = 9 group by OPERACION;

select * from SD_KARDEX_EFECTIVO where OPERACION = 'RETIRO DE AHORRO' and ID_CAJA = 9


select nvl(sum(IMPORTE_INTERES) , 0) from SD_PRESTAMOS_POR_SOCIOS where ESTADO != 'ANULADO' and FECHA BETWEEN TO_DATE('01-03-2025', 'DD-MM-YYYY')
    AND TO_DATE('01-08-2025', 'DD-MM-YYYY');
select  nvl(sum(IMPORTE_MORA) , 0) from SD_PRESTAMOS_MORA where FECHA BETWEEN TO_DATE('01-03-2025', 'DD-MM-YYYY')
                                          AND TO_DATE('01-08-2025', 'DD-MM-YYYY') and ESTADO != 'ANULADO';

select  nvl(sum(IMPORTE_A_PAGAR) , 0) ,  nvl(sum(INTERES_A_PAGAR) , 0) ,  nvl(sum(MORA_A_PAGAR) , 0) , nvl(sum(CONDONACION) , 0) from SD_PLAN_DE_PAGO p  where ESTADO = 'CANCELADO' and fecha_cancelado  BETWEEN TO_DATE('01-03-2025', 'DD-MM-YYYY')
    AND TO_DATE('31-03-2025', 'DD-MM-YYYY');
select * from SD_PAGO_DE_PRESTAMOS order by FECHA_REG asc;


update SD_PLAN_DE_PAGO set FECHA_CANCELADO = null  where ID_PLAN < -1;
commit ;
select count(1) from SD_PLAN_DE_PAGO where FECHA_CANCELADO is null;
select count(1) from SD_PLAN_DE_PAGO where FECHA_CANCELADO is not null;

select FECHA_CANCELADO , count(1) From SD_PLAN_DE_PAGO group by FECHA_CANCELADO ;
select FECHA_REG , count(1) from SD_PAGO_DE_PRESTAMOS group by FECHA_REG ;

select * from SD_PLAN_DE_PAGO order by FECHA_CANCELADO desc;
select * from SD_TIPOS_PRESTAMOS order by ID_TIPO desc;
select * from SD_PRESTAMOS_POR_SOCIOS where ID_TIPO_PRESTAMO =  7;
select * from SD_PAGO_DE_PRESTAMOS

         order by FECHA_REG desc;
select * from SD_PLAN_DE_PAGO where ID_PLAN = 234;
select * from SD_PLAN_DE_PAGO where ID_PRESTAMO = 234;
select * From SD_PRESTAMOS_POR_SOCIOS where NUMERO = 185;
select * from SD_CAJAS_CIERRES;
select * from SD_KARDEX_EFECTIVO order by ID_KARDEX asc;
select * from SD_RETIRO_SOCIO_MOVIL where ID_RETIRO = 521;
select * from SD_KARDEX_EFECTIVO where ID_CAJA = 9 and ID_OPERACION = 521;
INSERT INTO SINDICATO.SD_KARDEX_EFECTIVO (ID_KARDEX, ID_CAJA, ID_OPERACION, OPERACION, FECHA, DETALLE, INGRESO, EGRESO, SALDO, LOGIN, FECHA_REG, ESTADO, ID_CIERRE) VALUES (83751, 9, 521, 'RETIRO DE AHORRO', DATE '2025-06-24', 'PAGO  DE AHORRO  Movil 290: SALUSTIANO  MAIDA MONTAÑO', 0.00000, 100.00000, 64730.42000, 'maribel53', TIMESTAMP '2025-06-24 10:34:28', null, null);

select * from SD_KARDEX_SOCIO_MOVIL  where ID_OPERACION =  521;
INSERT INTO SINDICATO.SD_KARDEX_SOCIO_MOVIL (ID_KARDEX, ID_SOCIO_MOVIL, ID_OPERACION, OPERACION, FECHA, DETALLE, INGRESO, EGRESO, SALDO, LOGIN, FECHA_REG) VALUES (2051, 329, 521, 'RETIRO DE AHORRO', DATE '2025-06-24', 'AHORRO MES DE MAYO 2025', 0.00000, 100.00000, 0.00000, 'maribel53', TIMESTAMP '2025-06-24 10:34:28');

select * from SD_SOCIO_MOVILES where  ID_SOCIO_MOVIL =  329;
UPDATE SINDICATO.SD_SOCIO_MOVILES SET ID_SOCIO = 461, ID_MOVIL = 291, DESCRIPCION = null, TIPO_MOVIL = 'PRIMARIO', FECHA_ALTA = DATE '2009-03-07', FECHA_BAJA = null, OBSERVACION = null, FECHA_REG = TIMESTAMP '2025-02-27 19:11:16', ID_USR = 2, ESTADO = 'ACTIVO', SALDO = 100.00000, DEBE = null, USUARIO = null, PSW = null WHERE ID_SOCIO_MOVIL = 329;


select * from SD_PAGO_DE_PRESTAMOS where ESTADO = 'ANULADO' order by FECHA_REG desc;

SELECT FECHA, FECHA_REG, ID_PLAN, ID_PRESTAMO, TIPO
FROM SD_PAGO_DE_PRESTAMOS where ESTADO !='ANULADO'
ORDER BY FECHA_REG ASC;

select * from SD_PLAN_DE_PAGO where ID_PLAN = 97;
update SD_PLAN_DE_PAGO set FECHA_CANCELADO = null ;

select * from  SD_DETALLE_CAJA_CIERRE order by ID_CIERRE desc;
select * from SD_KARDEX_EFECTIVO where ID_CAJA = 9 order by ID_KARDEX desc;
select * from SD_KARDEX_EFECTIVO where ID_CAJA = 9 and ID_KARDEX = 126120;
INSERT INTO SINDICATO.SD_KARDEX_EFECTIVO (ID_KARDEX, ID_CAJA, ID_OPERACION, OPERACION, FECHA, DETALLE, INGRESO, EGRESO, SALDO, LOGIN, FECHA_REG, ESTADO, ID_CIERRE) VALUES (126120, 9, 61, 'INGRESOS', DATE '2025-08-19', 'DE LA CAJA DE AHORROS', 100.00000, 0.00000, 27634.42000, 'franzfgp', TIMESTAMP '2025-08-19 09:01:47', null, null);

select * from SD_INGRESOS where ID_INGRESO = 61;
select * from SD_INGRESOS where ID_INGRESO = 62;
INSERT INTO SINDICATO.SD_INGRESOS (ID_INGRESO, ID_CAJA, NRO_RECIBO, FECHA, CONCEPTO, OBSERVACION, IMPORTE, LOGIN, FECHA_REG, ESTADO) VALUES (61, 9, 0, DATE '2025-08-19', 'DE LA CAJA DE AHORROS', 'EN FECHA 24/06/25, SE HACE LA CANCELACION DE AHORRO AL AFILIADO SALUSTIANO MAIDA MONTAÑO DEL CODIGO 290, ESTE POR ERROR SE HACE EL PAGO DE LA CAJA COOPERATIVA, EN ESTE SENTIDO SE HACE LA DEVOLUCION A DICHA CAJA EL DINERO QUE SALIO DE DICHA CAJA', 100.00000, 'franzfgp', TIMESTAMP '2025-08-19 09:01:47', 'NUEVO');


select * from SD_EGRESOS order by ID_EGRESO desc;
select * from SD_CAJAS;
select * from SD_RETIRO_SOCIO_MOVIL;

select * from SD_MOVILES where NRO_MOVIL = 47;
select * from SD_MOVILES where ID_MOVIL = 47;
select * from SD_SOCIO_MOVILES where ID_MOVIL = 55;
select * from SD_SOCIO_MOVILES where ID_SOCIO_MOVIL = 55;

select * from SD_KARDEX_SOCIO_MOVIL where ID_SOCIO_MOVIL = 55 order by ID_KARDEX desc;
select * from SD_RETIRO_SOCIO_MOVIL_DETALLE;
select * from detalle
select * from SD_RETIRO_SOCIO_MOVIL_DETALLE;

select * from SD_SOCIO_MOVILES sm
    inner join SD_MOVILES m on m.ID_MOVIL = sm.ID_MOVIL
    inner join SD_SOCIOS s on s.ID_SOCIO = sm.ID_SOCIO
where m.NRO_MOVIL = 290;
select * from (
select query.ID_SOCIO_MOVIL , query.saldo1 , sm.SALDO from (
select ID_SOCIO_MOVIL , sum(TOTAL_AHORRO) , sum(TOTAL_CANCELADO) , (sum(TOTAL_AHORRO) - sum(TOTAL_CANCELADO) )as saldo1 from SD_DETALLE_CIERRES_AHORRO group by ID_SOCIO_MOVIL
                                                                                                                                           ) query inner join SD_SOCIO_MOVILES sm on query.ID_SOCIO_MOVIL = sm.ID_SOCIO_MOVIL
    ) query2 where SALDO <> saldo1;

select ESTADO , count(1) from SD_DETALLE_CIERRES_AHORRO group by ESTADO;
select ESTADO , count(1) from SD_DETALLE_CIERRES_AHORRO group by ESTADO;
select * from SD_CIERRES;
select * from SD_DETALLE_CIERRES_AHORRO where ID_SOCIO_MOVIL =55 order by ID_DETALLE desc;
update SD_DETALLE_CIERRES_AHORRO set TOTAL_CANCELADO = 0 where ID_SOCIO_MOVIL =  55;

select * from SD_RETIRO_SOCIO_MOVIL where ID_SOCIO_MOVIL = 55 order by ID_RETIRO desc;
select * from SD_RETIRO_SOCIO_MOVIL_DETALLE where ID_RETIRO in (
    select ID_RETIRO from SD_RETIRO_SOCIO_MOVIL where ID_SOCIO_MOVIL = 55

);

select ID_RETIRO , ESTADO from SD_RETIRO_SOCIO_MOVIL where ID_SOCIO_MOVIL = 55;

select * from SD_KARDEX_HOJAS where ID_SOCIO_MOVIL = 55;
INSERT INTO SINDICATO.SD_KARDEX_HOJAS (ID_KARDEX, ID_SOCIO_MOVIL, MES, CANT_HOJAS, CANT_REGULACIONES, CANT_HOJAS_OBLIG, LOGIN, FECHA_REG, DEBE) VALUES (3338, 55, DATE '2025-09-01', 4.00000, 0.00000, 20.00000, 'jhamila', TIMESTAMP '2025-09-01 15:22:37', 16);

SELECT
    job_name,
    COUNT(*) as total_ejecuciones,
    SUM(CASE WHEN status = 'SUCCEEDED' THEN 1 ELSE 0 END) as ejecuciones_exitosas,
    SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) as ejecuciones_fallidas,
    MIN(log_date) as primera_ejecucion,
    MAX(log_date) as ultima_ejecucion
FROM USER_SCHEDULER_JOB_LOG
WHERE job_name = 'JOB_ACT_KARDEX_HOJA_DAILY'
GROUP BY job_name;


SELECT job_name, enabled, state, next_run_date, last_start_date, last_run_duration
FROM USER_SCHEDULER_JOBS
WHERE job_name = 'JOB_ACT_KARDEX_HOJA_DAILY';