select * from SD_PRESTAMOS_POR_SOCIOS order by ID_PRESTAMO asc
;
delete from SD_PRESTAMOS_POR_SOCIOS where ID_PRESTAMO > -1;
select * from SD_PLAN_DE_PAGO order by ID_PRESTAMO asc , NRO_SEMANA asc;
delete from SD_PLAN_DE_PAGO where ID_PLAN > -1;
select * from SD_PAGO_DE_PRESTAMOS order by ID_PRESTAMO asc;
delete from SD_PAGO_DE_PRESTAMOS where ID_PAGO > -1;
delete from SD_PRESTAMOS_MORA where ID_MORA > -1;
select * from SD_PAGO_DE_PRESTAMOS;
select * from SD_KARDEX_EFECTIVO where OPERACION = 'PAGO PRESTAMO' and ID_OPERACION in (select ID_PAGO from SD_PAGO_DE_PRESTAMOS);
select * from SD_KARDEX_EFECTIVO where OPERACION = 'PAGO MORA' and ID_OPERACION in (select ID_PAGO from SD_PAGO_DE_PRESTAMOS);
delete from SD_KARDEX_EFECTIVO where OPERACION = 'PAGO PRESTAMO' and ID_OPERACION in (select ID_PAGO from SD_PAGO_DE_PRESTAMOS);
delete from SD_KARDEX_EFECTIVO where OPERACION = 'PAGO MORA';

select * from SD_KARDEX_EFECTIVO where OPERACION = 'PRESTAMOS' and ID_OPERACION in (select ID_PRESTAMO from SD_PRESTAMOS_POR_SOCIOS);
delete from SD_KARDEX_EFECTIVO where OPERACION = 'PRESTAMOS' and ID_OPERACION in (select ID_PRESTAMO from SD_PRESTAMOS_POR_SOCIOS);


INSERT INTO SINDICATO_132.SD_MENU_OPCIONES (ID_OPC, OPCION, LINK, TOOLTIP, ICONO, ESTILO, ID_PADRE, ESTADO, ORDEN)
VALUES (36, 'Gestion', 'App.View.Gestion.Principal', 'Cierre de Gestion', 'application-settings-icon', null, null, 'A', 13);

INSERT INTO SINDICATO_132.SD_GESTION (ID_GESTION, CODIGO, DESCRIPCION, FECHA_INICIO, FECHA_FIN, FECHA_REG, ESTADO, LOGIN, SALDO_A_FAVOR, SALDO_POR_COBRAR, OBSERVACION_CIERRE) VALUES (1, '2023', 'Gestion 2023', DATE '2021-04-01', DATE '2023-03-12', TIMESTAMP '2023-01-13 21:52:27', 'ACTIVO', 'admin', null,null, '');

INSERT INTO SINDICATO_132.SD_TIPOS_PRESTAMOS (ID_TIPO, ID_CAJA, NOMBRE, OBSERVACION, ESTADO, MONEDA, IMPORTE_MAXIMO, IMPORTE_MINIMO, INTERES, MULTA_POR_MORA, SEMANAS, FECHA_REG, LOGIN_USR, CATEGORIA, INTERES_FIJO, TIPO_INTERES, DIAS_ESPERA_MORA) VALUES (5, 19, 'LARGO PLAZO 2000X15', 'APOYO A FIDELIDAD DOS', 'ACTIVO', 'BOLIVIANOS', 2000.00, 0.00, 7.00, 0.00, 15, TIMESTAMP '2017-02-11 11:01:25', 'admin', 'LARGO PLAZO', 0.00, 'INTERES', 0);
INSERT INTO SINDICATO_132.SD_TIPOS_PRESTAMOS (ID_TIPO, ID_CAJA, NOMBRE, OBSERVACION, ESTADO, MONEDA, IMPORTE_MAXIMO, IMPORTE_MINIMO, INTERES, MULTA_POR_MORA, SEMANAS, FECHA_REG, LOGIN_USR, CATEGORIA, INTERES_FIJO, TIPO_INTERES, DIAS_ESPERA_MORA) VALUES (8, 19, 'CORTO PLAZO 1500X15', 'CORTO PLAZO', 'ACTIVO', 'BOLIVIANOS', 1500.00, 0.00, 7.00, 7.00, 15, TIMESTAMP '2017-06-28 09:45:16', 'admin', 'CORTO PLAZO', 0.00, 'INTERES', 5);
INSERT INTO SINDICATO_132.SD_TIPOS_PRESTAMOS (ID_TIPO, ID_CAJA, NOMBRE, OBSERVACION, ESTADO, MONEDA, IMPORTE_MAXIMO, IMPORTE_MINIMO, INTERES, MULTA_POR_MORA, SEMANAS, FECHA_REG, LOGIN_USR, CATEGORIA, INTERES_FIJO, TIPO_INTERES, DIAS_ESPERA_MORA) VALUES (7, 19, 'LARGO PLAZO 3000X20', 'APOYO A FIDELIDAD UNO
', 'ACTIVO', 'BOLIVIANOS', 3000.00, 0.00, 7.00, 10.00, 20, TIMESTAMP '2017-03-27 08:57:11', 'admin', 'LARGO PLAZO', 0.00, 'INTERES', 5);
INSERT INTO SINDICATO_132.SD_TIPOS_PRESTAMOS (ID_TIPO, ID_CAJA, NOMBRE, OBSERVACION, ESTADO, MONEDA, IMPORTE_MAXIMO, IMPORTE_MINIMO, INTERES, MULTA_POR_MORA, SEMANAS, FECHA_REG, LOGIN_USR, CATEGORIA, INTERES_FIJO, TIPO_INTERES, DIAS_ESPERA_MORA) VALUES (2, 19, 'EMERGENCIA 500X6', 'PRESTAMO A CORTO PLAZO CON INTERES  DE MONTO FIJO', 'ACTIVO', 'BOLIVIANOS', 500.00, 0.00, 7.00, 35.00, 6, TIMESTAMP '2017-01-03 21:41:31', 'admin', 'CORTO PLAZO', 0.00, 'INTERES', 0);
INSERT INTO SINDICATO_132.SD_TIPOS_PRESTAMOS (ID_TIPO, ID_CAJA, NOMBRE, OBSERVACION, ESTADO, MONEDA, IMPORTE_MAXIMO, IMPORTE_MINIMO, INTERES, MULTA_POR_MORA, SEMANAS, FECHA_REG, LOGIN_USR, CATEGORIA, INTERES_FIJO, TIPO_INTERES, DIAS_ESPERA_MORA) VALUES (3, 19, 'EMERGENCIA 1000X10', 'PRESTAMO A LARGO PLAZO', 'ACTIVO', 'BOLIVIANOS', 1000.00, 0.00, 7.00, 70.00, 10, TIMESTAMP '2017-01-03 21:42:33', 'admin', 'LARGO PLAZO', 0.00, 'INTERES', 7);
INSERT INTO SINDICATO_132.SD_TIPOS_PRESTAMOS (ID_TIPO, ID_CAJA, NOMBRE, OBSERVACION, ESTADO, MONEDA, IMPORTE_MAXIMO, IMPORTE_MINIMO, INTERES, MULTA_POR_MORA, SEMANAS, FECHA_REG, LOGIN_USR, CATEGORIA, INTERES_FIJO, TIPO_INTERES, DIAS_ESPERA_MORA) VALUES (9, 19, 'REGULACIONES 2022', 'REGULACIONES 2022 POR TEMA DE AJUSTES', 'ACTIVO', 'BOLIVIANOS', 2500.00, 0.00, 0.00, 0.00, 12, TIMESTAMP '2023-01-06 20:05:40', 'admin', 'EMERGENCIAS', 0.00, 'INTERES', 0);


select * from SD_LISTAS_ITEMS w order by ID_TABLA desc;
select * from SD_GESTION;
INSERT INTO SINDICATO_132.SD_LISTAS_ITEMS (ID_TABLA, ID_PADRE, ID_LISTA, CODIGO, VALOR, ESTADO) VALUES (1049, null, 20, '122', 'REPORTE TOP DEUDORES POR GESTION', 'A');
INSERT INTO SINDICATO_132.SD_LISTAS_ITEMS (ID_TABLA, ID_PADRE, ID_LISTA, CODIGO, VALOR, ESTADO) VALUES (1050, null, 20, '22', 'REPORTE TOTAL DE PRESTAMOS POR GESTION', 'A');

select * from SD_PRESTAMOS_POR_SOCIOS order by ID_PRESTAMO desc;
select FECHA_PAGO , FECHA_PAGO - 30 from SD_PLAN_DE_PAGO where ID_PRESTAMO = 6 order by FECHA_PAGO asc;

update SD_PLAN_DE_PAGO set FECHA_PAGO  = FECHA_PAGO - 30 where ID_PRESTAMO = 7;


select plan.*,
                          stp.DIAS_ESPERA_MORA,
                          STP.ID_TIPO,
                          stp.MULTA_POR_MORA,
                          TO_DATE(to_char(current_date - (1 + stp.DIAS_ESPERA_MORA), 'DD/MM/YYYY'), 'DD/MM/YYYY') -
                          plan.FECHA_PAGO as DIAS_RETRASADOS
                   from SD_PLAN_DE_PAGO plan
                            inner join SINDICATO_132.SD_PRESTAMOS_POR_SOCIOS SPPS on SPPS.ID_PRESTAMO = plan.ID_PRESTAMO
                            inner join SD_TIPOS_PRESTAMOS STP on STP.ID_TIPO = SPPS.ID_TIPO_PRESTAMO
                   where plan.ESTADO = 'NUEVO'
                     and plan.FECHA_PAGO < current_date
                   order by  plan.ID_PRESTAMO  asc , plan.NRO_SEMANA asc


select * from SD_GESTION;
delete from SD_DETALLE_CIERRE_GESTION where ID_DETALLE > -1
INSERT into SINDICATO_132.SD_PRESTAMOS_POR_SOCIOS
select p.* , 1 , null ,  0, null  from SINDICATO_132_032023.SD_PRESTAMOS_POR_SOCIOS  p order by ID_PRESTAMO asc

INSERT into SINDICATO_132.SD_KARDEX_EFECTIVO
select * from  SINDICATO_132_032023.SD_KARDEX_EFECTIVO where OPERACION = 'PRESTAMOS';
select * from SINDICATO_132.SD_PLAN_DE_PAGO;


select q1.* , q1.semanas_ca * (q1.importe + q1.interes) - q1.cancelado as dif  from (select q.*, round(q.cancelado / (q.importe + q.interes), 0) as semanas_ca
               from (select sum(IMPORTE)                                           as cancelado,
                            round(min(pre.IMPORTE_PRESTAMO) / min(pre.SEMANAS),0) as importe,
                            round(min(pre.IMPORTE_INTERES) / min(pre.SEMANAS), 0)  as interes,
                            round(min(pre.IMPORTE_INTERES) / min(pre.SEMANAS), 2)  as interes_2,
                             round(min(pre.IMPORTE_PRESTAMO) / min(pre.SEMANAS), 2)  as importe_2,
                            min(pre.SEMANAS)                                       as semanas,
                            min(pre.ID_PRESTAMO) as id
                     from SINDICATO_132_032023.SD_PAGO_DE_PRESTAMOS p
                              inner join SINDICATO_132_032023.SD_PRESTAMOS_POR_SOCIOS pre
                                         on p.ID_PRESTAMO = pre.ID_PRESTAMO
                     where p.estado != 'ANULADO'
                       and p.ID_PRESTAMO in (select SD_PRESTAMOS_POR_SOCIOS.ID_PRESTAMO
                                             from SINDICATO_132.SD_PRESTAMOS_POR_SOCIOS
                                             where NUMERO = 13)
                     order by p.ID_PAGO desc) q )q1



select * from SINDICATO_132_032023.SD_PAGO_DE_PRESTAMOS p
                    inner join SINDICATO_132_032023.SD_PRESTAMOS_POR_SOCIOS pre on p.ID_PRESTAMO = pre.ID_PRESTAMO
                    where p.estado != 'ANULADO' and p.ID_PRESTAMO in(
    select SD_PRESTAMOS_POR_SOCIOS.ID_PRESTAMO from SINDICATO_132.SD_PRESTAMOS_POR_SOCIOS where NUMERO = 22
    ) order by p.ID_PAGO desc;



delete from SD_PLAN_DE_PAGO where ID_PRESTAMO <> 25;
delete from SD_PAGO_DE_PRESTAMOS where ID_PRESTAMO <> 25;
select * from SD_PLAN_DE_PAGO;

INSERT into SINDICATO_132.SD_PLAN_DE_PAGO

SELECT * FROM SD_PLAN_DE_PAGO
AS OF TIMESTAMP
TO_TIMESTAMP('2023-03-18 14:10:00', 'YYYY-MM-DD HH24:MI:SS');



INSERT into SINDICATO_132.SD_PAGO_DE_PRESTAMOS

SELECT * FROM SD_PAGO_DE_PRESTAMOS
AS OF TIMESTAMP
TO_TIMESTAMP('2023-03-18 14:10:00', 'YYYY-MM-DD HH24:MI:SS');


delete from SD_PLAN_DE_PAGO where ID_PRESTAMO = 14;
delete from SD_PAGO_DE_PRESTAMOS where ID_PRESTAMO = 14;
delete from SD_PAGO_DE_PRESTAMOS where ID_PRESTAMO = 6;

select sum(IMPORTE) from SINDICATO_132_032023.SD_PAGO_DE_PRESTAMOS where ESTADO <>  'ANULADO'
select * from SINDICATO_132_032023.SD_PAGO_DE_PRESTAMOS order by FECHA_REG desc
select sum(IMPORTE) from SINDICATO_132.SD_PAGO_DE_PRESTAMOS where ESTADO <>  'ANULADO'

select p.ID_PRESTAMO,p.NUMERO    ,
       (select sum(IMPORTE) from SINDICATO_132_032023.SD_PAGO_DE_PRESTAMOS where ESTADO <>  'ANULADO' and ID_PRESTAMO = p.ID_PRESTAMO  ) as total1 ,
              (select sum(IMPORTE) from SINDICATO_132.SD_PAGO_DE_PRESTAMOS where ESTADO <>  'ANULADO' and ID_PRESTAMO = p.ID_PRESTAMO  ) as total1


       from SD_PRESTAMOS_POR_SOCIOS p where ESTADO <> 'ANULADO';


select * from SD_PRESTAMOS_POR_SOCIOS where NUMERO = 45;
select sum(IMPORTE_A_PAGAR) , sum(INTERES_A_PAGAR) from SD_PLAN_DE_PAGO where ID_PRESTAMO = 48 order by NRO_SEMANA asc