SET DEFINE OFF;
DELETE FROM SINDICATO_131.SD_LISTAS_ITEMS WHERE ID_LISTA = 20;
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1030, 20, '0', 
    'REPORTE ESTADO RESULTADO POR CAJA', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1031, 20, '-1', 
    'REPORTE ESTADO RESULTADO POR MONEDA', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1032, 20, '-2', 
    'REPORTE MATRIZ POR AHORRO', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1033, 20, '-3', 
    'REPORTE MATRIZ POR AHORRO CANCELADOS', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1034, 20, '-4', 
    'REPORTE MATRIZ POR AHORRO/DEBE', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1025, 20, '12', 
    'REPORTE DEUDORES COPERATIVA', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1015, 20, '5', 
    'REPORTE EGRESOS', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1011, 20, '1', 
    'REPORTE DETALLE DE HOJAS', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1012, 20, 'Q', 
    'REPORTE INGRESOS TOTALES', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1013, 20, '3', 
    'REPORTE SOCIOS ACTIVOS', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1014, 20, '4', 
    'REPORTE INGRESOS DETALLE', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1020, 20, '6', 
    'REPORTE INGRESOS DETALLE POR CAJA', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1021, 20, '7', 
    'REPORTE DETALLE VENTAS DE HOJAS', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1022, 20, '8', 
    'REPORTE DETALLE REGULARIZADAS', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1023, 20, '10', 
    'REPORTES DETALLE DE PRESTAMOS Y PAGOS', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1024, 20, '11', 
    'REPORTE TOTAL DE PRESTAMOS', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1026, 20, '13', 
    'REPORTE DEUDORES COPERATIVA CUOTA', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1027, 20, '14', 
    'REPORTE DEUDORES POR HOJA', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1028, 20, '15', 
    'REPORTE COMPRA DE HOJAS POR SOCIO', 'A');
Insert into SINDICATO_131.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1029, 20, '16', 
    'REPORTE AHORROS Y RETIROS POR SOCIO', 'A');
COMMIT;
