SET DEFINE OFF;
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1030, 20, '0', 
    'REPORTE ESTADO RESULTADO POR CAJA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1031, 20, '-1', 
    'REPORTE ESTADO RESULTADO POR MONEDA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1032, 20, '-2', 
    'REPORTE MATRIZ POR AHORRO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1033, 20, '-3', 
    'REPORTE MATRIZ POR AHORRO CANCELADOS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1034, 20, '-4', 
    'REPORTE MATRIZ POR AHORRO/DEBE', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1025, 20, '12', 
    'REPORTE DEUDORES COPERATIVA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1015, 20, '5', 
    'REPORTE EGRESOS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1008, 19, '01', 
    'CORTO PLAZO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1009, 19, '02', 
    'LARGO PLAZO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1010, 19, '03', 
    'EMERGENCIAS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (65, 16, '0', 
    'CERTIFICADO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (66, 16, '1', 
    'CARTA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (67, 16, '2', 
    'RECIBO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (68, 6, '3', 
    'CAMIONETA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (69, 13, '4', 
    'NEGRO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (55, 5, '1', 
    'PRIMARIO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (56, 5, '2', 
    'SECUNDARIO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (57, 6, '1', 
    'VAGONETA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (58, 6, '2', 
    'AUTOMOVIL', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (59, 13, '1', 
    'ROJO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (60, 13, '2', 
    'BLANCO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (61, 14, '1', 
    'TOYOTA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (62, 14, '2', 
    'NISSAN', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (20, 10, '1', 
    'ASIGNACION', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (21, 10, '2', 
    'ADICIONAL', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (22, 9, '2014', 
    '2014', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (23, 11, '1', 
    'OTROS INGRESOS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (24, 11, '2', 
    'OTROS EGRESOS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (25, 12, 'BOB', 
    'BOLIVIANOS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1, 7, '01', 
    'ENERO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (2, 7, '02', 
    'FEBRERO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (3, 7, '03', 
    'MARZO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (7, 7, '06', 
    'JUNIO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (5, 7, '04', 
    'ABRIL', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (6, 7, '05', 
    'MAYO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (8, 7, '07', 
    'JULIO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (9, 7, '08', 
    'AGOSTO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (10, 7, '09', 
    'SEPTIEMBRE', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (11, 7, '10', 
    'OCTUBRE', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (12, 7, '11', 
    'NOVIEMBRE', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (13, 7, '12', 
    'DICIEMBRE', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (14, 8, '1', 
    'DIA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (15, 8, '2', 
    'TARDE', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (16, 8, '3', 
    'NOCHE', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (17, 9, '2012', 
    '2012', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (18, 9, '2013', 
    '2013', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (4, 1, 'CBBA', 
    'COCHABAMBA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (19, 1, 'OR', 
    'ORURO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (26, 1, 'SCZ', 
    'SANTACRUZ', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (27, 1, 'LPZ', 
    'LAPAZ', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (28, 1, 'TRJ', 
    'TARIJA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (29, 1, 'CH', 
    'CHUQUISACA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (30, 1, 'PA', 
    'PANDO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (31, 1, 'BN', 
    'BENI', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (32, 2, 'A', 
    'A', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (33, 2, 'B', 
    'B', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (34, 2, 'C', 
    'C', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (35, 3, 'CASA', 
    'CASADO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (37, 3, 'SOL', 
    'SOLTERO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (38, 3, 'VIU', 
    'VIUDO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (39, 3, 'DIV', 
    'DIVORCIADO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (40, 3, 'SEP', 
    'SEPARADO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (41, 1, 'SUC', 
    'SUCRE', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (53, 4, '1', 
    'ESPOSA(O)', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (54, 4, '2', 
    'HIJOS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (63, 15, '1', 
    'MAL COMPORTAMIENTO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (64, 15, '2', 
    'FALTA A REUNIONES', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (71, 17, '01', 
    'PERMISOS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (72, 17, '02', 
    'SANCIONES', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (73, 17, '03', 
    'VARIOS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1001, 18, '01', 
    'DIRIGENTES 2016', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1002, 18, '02', 
    'FUERZA MAYOR', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1003, 18, '03', 
    'LICENCIA ', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1000, 12, 'SUS', 
    'DOLARES', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1007, 18, '04', 
    'EXTRAORDINARIO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1004, 13, '3', 
    'PLOMO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1005, 13, '5', 
    'VERDE', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1006, 14, '3', 
    'SUZUKI', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1011, 20, '1', 
    'REPORTE DETALLE DE HOJAS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1012, 20, 'Q', 
    'REPORTE INGRESOS TOTALES', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1013, 20, '3', 
    'REPORTE SOCIOS ACTIVOS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1014, 20, '4', 
    'REPORTE INGRESOS DETALLE', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1020, 20, '6', 
    'REPORTE INGRESOS DETALLE POR CAJA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1021, 20, '7', 
    'REPORTE DETALLE VENTAS DE HOJAS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1022, 20, '8', 
    'REPORTE DETALLE REGULARIZADAS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1023, 20, '10', 
    'REPORTES DETALLE DE PRESTAMOS Y PAGOS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1024, 20, '11', 
    'REPORTE TOTAL DE PRESTAMOS', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1026, 20, '13', 
    'REPORTE DEUDORES COPERATIVA CUOTA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1027, 20, '14', 
    'REPORTE DEUDORES POR HOJA', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1028, 20, '15', 
    'REPORTE COMPRA DE HOJAS POR SOCIO', 'A');
Insert into SINDICATO_132.SD_LISTAS_ITEMS
   (ID_TABLA, ID_LISTA, CODIGO, VALOR, ESTADO)
 Values
   (1029, 20, '16', 
    'REPORTE AHORROS Y RETIROS POR SOCIO', 'A');
COMMIT;
