--1. se crea la tabla SD_GESTION
ALTER TABLE SINDICATO_132.SD_GESTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE SINDICATO_132.SD_GESTION CASCADE CONSTRAINTS;

CREATE TABLE SINDICATO_132.SD_GESTION
(
  ID_GESTION    NUMBER(7)                       NOT NULL,
  CODIGO        VARCHAR2(20 BYTE)               NOT NULL,
  DESCRIPCION   VARCHAR2(1500 BYTE),
  FECHA_INICIO  DATE                            NOT NULL,
  FECHA_FIN     DATE,
  FECHA_REG     DATE,
  ESTADO        VARCHAR2(50 BYTE)               NOT NULL,
  LOGIN         VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SINDICATO_132.SD_GESTION_PK ON SINDICATO_132.SD_GESTION
(ID_GESTION)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SINDICATO_132.SD_GESTION ADD (
  CONSTRAINT SD_GESTION_PK
 PRIMARY KEY
 (ID_GESTION)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
SET DEFINE OFF;
Insert into SINDICATO_132.SD_GESTION
   (ID_GESTION, CODIGO, DESCRIPCION, FECHA_INICIO, FECHA_FIN, 
    FECHA_REG, ESTADO, LOGIN)
 Values
   (1, '2023-2024', 'Directorio 2022-2024', TO_DATE('04/01/2021 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 
    TO_DATE('01/13/2023 21:52:27', 'MM/DD/YYYY HH24:MI:SS'), 'ACTIVO', 'admin');
COMMIT;

--SE MODIFICO LA TABLA SD_PRESTAMOS_SOCIOS
CREATE TABLE SINDICATO_132.SD_PRESTAMOS_POR_SOCIOS
(
  ID_PRESTAMO          NUMBER(7)                NOT NULL,
  ID_SOCIO_MOVIL       NUMBER(7)                NOT NULL,
  ID_TIPO_PRESTAMO     NUMBER(7)                NOT NULL,
  ID_CAJA              NUMBER(7)                NOT NULL,
  FECHA                DATE                     NOT NULL,
  IMPORTE_PRESTAMO     NUMBER(15,2)             NOT NULL,
  MONEDA               VARCHAR2(20 BYTE),
  OBSERVACION          VARCHAR2(255 BYTE),
  INTERES              NUMBER(6,2)              NOT NULL,
  SEMANAS              NUMBER(7)                NOT NULL,
  SALDO                NUMBER(15,2)             NOT NULL,
  ESTADO               VARCHAR2(20 BYTE),
  FECHA_REG            DATE,
  LOGIN_USR            VARCHAR2(20 BYTE),
  FECHA_LIMITE_PAGO    DATE,
  TIPO_INTERES         VARCHAR2(50 BYTE),
  IMPORTE_INTERES      NUMBER(15,2),
  ESTADO_CIERRE        VARCHAR2(50 BYTE)        DEFAULT 'NUEVO',
  SALDO_CAPITAL        NUMBER(15,2),
  SALDO_INTERES        NUMBER(15,2),
  ID_GESTION           NUMBER(7),
  NUMERO               NUMBER(7),
  CONDONACION_INTERES  NUMBER(15,2),
  ID_PRESTAMO_REF      NUMBER(7)
)

se crearon las siguientes funciones
 SINDICATO_132.P_SD_OBTENER_NRO
 SINDICATO_132.P_ACT_NRO_PRESTAMO
 SINDICATO_132.P_SD_OBTENER_GESTION
